const SUPABASE_URL = 'https://gepytsrxtwplujflkwcd.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_A79aZ2laC6WxNKJcecsX_g_qchrLxsZ';
const hasSupabaseConfig = !SUPABASE_URL.includes('YOUR-') && !SUPABASE_ANON_KEY.includes('YOUR-');
const supabaseClient = hasSupabaseConfig && window.supabase ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const storageKey = 'pressledger-demo-data';
const state = { owners: [], transactions: [], periods: [], selectedPeriod: null };
const money = value => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value) || 0);
const dateLabel = value => new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`));
const monthName = value => new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(new Date(`${value}-01T00:00:00`));
const periodMonthKey = name => { const months = ['januari', 'februari', 'maret', 'april', 'mei', 'juni', 'juli', 'agustus', 'september', 'oktober', 'november', 'desember']; const parts = name.toLowerCase().trim().split(/\s+/); const month = months.indexOf(parts[0]); return month >= 0 && /^\d{4}$/.test(parts[1]) ? `${parts[1]}-${String(month + 1).padStart(2, '0')}` : ''; };
const initials = name => name.split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase();
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;

function seedData() {
  if (supabaseClient) return;
  const saved = localStorage.getItem(storageKey);
  if (saved) Object.assign(state, JSON.parse(saved));
  else {
    state.owners = [{ id: uid(), nama: 'Aditya Pranata', created_at: '2026-01-01' }, { id: uid(), nama: 'Maya Lestari', created_at: '2026-01-01' }];
    state.transactions = [{ id: uid(), pemilik_id: state.owners[0].id, tanggal: '2026-01-05', jenis: 'setoran', jumlah: 75000000, keterangan: 'Setoran modal awal', no_bukti: 'BM-2601-001', created_at: '2026-01-05' }, { id: uid(), pemilik_id: state.owners[1].id, tanggal: '2026-01-08', jenis: 'setoran', jumlah: 50000000, keterangan: 'Setoran modal awal', no_bukti: 'BM-2601-002', created_at: '2026-01-08' }, { id: uid(), pemilik_id: state.owners[0].id, tanggal: '2026-01-18', jenis: 'prive', jumlah: 5000000, keterangan: 'Pengambilan pribadi', no_bukti: 'PV-2601-001', created_at: '2026-01-18' }, { id: uid(), pemilik_id: state.owners[1].id, tanggal: '2026-01-30', jenis: 'laba', jumlah: 18500000, keterangan: 'Laba bersih Januari', no_bukti: 'LP-2601-001', created_at: '2026-01-30' }];
    state.periods = [{ id: uid(), nama_periode: 'Januari 2026', modal_awal: 0, created_at: '2026-01-31' }];
    persist();
  }
}
function persist() { if (!supabaseClient) localStorage.setItem(storageKey, JSON.stringify({ owners: state.owners, transactions: state.transactions, periods: state.periods })); }
function setConnectionStatus(message, connected = false) { const status = document.querySelector('#connection-status'); const dot = document.querySelector('.status-dot'); status.textContent = message; dot.style.background = connected ? '#8bd5a4' : '#e08b72'; }
async function loadData() {
  if (!supabaseClient) return;
  const results = await Promise.all([supabaseClient.from('pemilik').select('*').order('nama'), supabaseClient.from('transaksi_modal').select('*').order('tanggal', { ascending: false }), supabaseClient.from('periode_laporan').select('*').order('created_at', { ascending: false })]);
  const failed = results.find(result => result.error);
  if (failed) throw failed.error;
  const [{ data: owners }, { data: transactions }, { data: periods }] = results;
  state.owners = owners || []; state.transactions = transactions || []; state.periods = periods || [];
  setConnectionStatus('Supabase tersambung', true);
}
async function insertRecord(table, record) { if (supabaseClient) { const { data, error } = await supabaseClient.from(table).insert(record).select().single(); if (error) throw error; return data; } return { ...record, id: uid(), created_at: new Date().toISOString() }; }
async function updateRecord(table, id, record) { if (supabaseClient) { const response = await fetch(`${SUPABASE_URL}/rest/v1/${table}?id=eq.${encodeURIComponent(id)}`, { method: 'PATCH', headers: { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}`, 'Content-Type': 'application/json', Prefer: 'return=representation' }, body: JSON.stringify(record) }); const body = await response.text(); if (!response.ok) throw new Error(body || `Gagal memperbarui ${table}.`); const rows = body ? JSON.parse(body) : []; if (!rows.length) throw new Error('Data laporan tidak ditemukan atau tidak dapat diperbarui.'); return rows[0]; } return { ...record, id }; }
async function deleteRecord(table, id) { if (supabaseClient) { const { error } = await supabaseClient.from(table).delete().eq('id', id); if (error) throw error; } }
function ownerById(id) { return state.owners.find(owner => owner.id === id); }
function transactionTotals(transactions = state.transactions) { return transactions.reduce((total, item) => { const amount = Number(item.jumlah); if (item.jenis === 'setoran') total.setoran += amount; if (item.jenis === 'prive') total.prive += amount; if (item.jenis === 'laba') total.laba += amount; if (item.jenis === 'rugi') total.rugi += amount; return total; }, { setoran: 0, prive: 0, laba: 0, rugi: 0 }); }
function endingCapital(opening = 0, totals = transactionTotals()) { return Number(opening) + totals.setoran - totals.prive + totals.laba - totals.rugi; }
function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
function fitStatValues() { document.querySelectorAll('.stat-value').forEach(value => { value.style.fontSize = '25px'; while (value.scrollWidth > value.clientWidth && parseFloat(value.style.fontSize) > 7) value.style.fontSize = `${parseFloat(value.style.fontSize) - 1}px`; }); }
function renderStats() { const totals = transactionTotals(); document.querySelector('#stat-equity').textContent = money(endingCapital(0, totals)); document.querySelector('#stat-deposit').textContent = money(totals.setoran); document.querySelector('#stat-withdrawal').textContent = money(totals.prive); document.querySelector('#stat-profit').textContent = money(totals.laba - totals.rugi); document.querySelector('#stat-equity-meta').textContent = `${state.transactions.length} transaksi tercatat`; document.querySelector('#stat-profit-meta').textContent = totals.rugi ? `${money(totals.rugi)} rugi tercatat` : 'Hasil periode berjalan'; fitStatValues(); }
function renderOwnerOptions() { const options = state.owners.map(owner => `<option value="${owner.id}">${owner.nama}</option>`).join(''); document.querySelector('#transaction-owner').innerHTML = options || '<option value="">Tambahkan pemilik dulu</option>'; document.querySelector('#transaction-owner-filter').innerHTML = `<option value="">Semua pemilik</option>${options}`; updateOwnerRequirement(); }
function updateOwnerRequirement() { const type = document.querySelector('#transaction-type')?.value; const ownerField = document.querySelector('#transaction-owner-field'); const owner = document.querySelector('#transaction-owner'); const needsOwner = type === 'setoran' || type === 'prive'; owner.disabled = !needsOwner; owner.required = needsOwner; ownerField.classList.toggle('optional-owner', !needsOwner); if (!needsOwner) owner.value = ''; }
function renderRecent() { const target = document.querySelector('#recent-transactions'); const rows = [...state.transactions].sort((a, b) => b.tanggal.localeCompare(a.tanggal)).slice(0, 5); target.innerHTML = rows.length ? rows.map(item => { const owner = !['laba', 'rugi'].includes(item.jenis) ? ownerById(item.pemilik_id)?.nama : ''; return `<div class="activity-item"><div class="activity-icon ${item.jenis}">${item.jenis === 'prive' ? '↘' : item.jenis === 'rugi' ? '−' : '↗'}</div><div class="activity-info"><strong>${item.keterangan || item.jenis}</strong><span>${owner ? `${owner} · ` : ''}${dateLabel(item.tanggal)}</span></div><div class="activity-amount ${['prive','rugi'].includes(item.jenis) ? 'amount-negative' : 'amount-positive'}">${['prive','rugi'].includes(item.jenis) ? '-' : '+'}${money(item.jumlah)}</div></div>`; }).join('') : '<div class="empty-state">Belum ada transaksi.</div>'; }
function renderOwnerSummary() { const target = document.querySelector('#owner-summary-list'); target.innerHTML = state.owners.length ? state.owners.map(owner => { const total = transactionTotals(state.transactions.filter(item => item.pemilik_id === owner.id)); return `<div class="owner-row"><div class="owner-avatar">${initials(owner.nama)}</div><div><strong>${owner.nama}</strong><span>Modal bersih ${money(total.setoran - total.prive)}</span></div></div>`; }).join('') : '<div class="empty-state">Belum ada pemilik.</div>'; }
function renderOwners() { document.querySelector('#owners-grid').innerHTML = state.owners.length ? state.owners.map(owner => { const total = transactionTotals(state.transactions.filter(item => item.pemilik_id === owner.id)); return `<article class="owner-card"><button class="delete-owner" data-delete-owner="${owner.id}" title="Hapus pemilik">×</button><div class="owner-card-head"><div class="owner-avatar">${initials(owner.nama)}</div><div><h2>${owner.nama}</h2><p>Terdaftar ${dateLabel(owner.created_at.slice(0, 10))}</p></div></div><div class="owner-card-stat"><span>Modal bersih</span><strong>${money(total.setoran - total.prive + total.laba - total.rugi)}</strong></div></article>`; }).join('') : '<div class="empty-state">Belum ada data pemilik. Tambahkan pemilik untuk mulai mencatat.</div>'; }
function filteredTransactions() { const search = document.querySelector('#transaction-search').value.toLowerCase(); const owner = document.querySelector('#transaction-owner-filter').value; const type = document.querySelector('#transaction-type-filter').value; const month = document.querySelector('#transaction-month-filter').value; return state.transactions.filter(item => (!search || `${item.keterangan} ${item.no_bukti}`.toLowerCase().includes(search)) && (!owner || item.pemilik_id === owner) && (!type || item.jenis === type) && (!month || item.tanggal.startsWith(month))).sort((a, b) => b.tanggal.localeCompare(a.tanggal)); }
function renderTransactions() { const rows = filteredTransactions(); document.querySelector('#transaction-table-body').innerHTML = rows.length ? rows.map(item => `<tr><td>${dateLabel(item.tanggal)}</td><td>${['laba','rugi'].includes(item.jenis) ? '-' : ownerById(item.pemilik_id)?.nama || '-'}</td><td><span class="type-badge ${item.jenis}">${item.jenis[0].toUpperCase() + item.jenis.slice(1)}</span></td><td>${item.keterangan || '-'}</td><td>${item.no_bukti || '-'}</td><td class="align-right ${['prive','rugi'].includes(item.jenis) ? 'amount-negative' : 'amount-positive'}">${['prive','rugi'].includes(item.jenis) ? '-' : '+'}${money(item.jumlah)}</td><td class="align-right"><button class="table-action" data-delete-transaction="${item.id}" title="Hapus transaksi">×</button></td></tr>`).join('') : '<tr><td colspan="7"><div class="empty-state">Tidak ada transaksi yang sesuai filter.</div></td></tr>'; }
function renderChart() { const year = document.querySelector('#chart-year').value || new Date().getFullYear(); const chart = document.querySelector('#monthly-chart'); const monthTotals = Array.from({ length: 12 }, (_, month) => transactionTotals(state.transactions.filter(item => item.tanggal.startsWith(`${year}-${String(month + 1).padStart(2, '0')}`)))); const max = Math.max(100000000, ...monthTotals.map(item => Math.max(item.setoran, item.prive, item.laba, item.rugi))); chart.innerHTML = monthTotals.map(item => `<div class="bar-group"><i class="bar deposit" style="height:${item.setoran / max * 100}%"></i><i class="bar withdrawal" style="height:${item.prive / max * 100}%"></i><i class="bar profit" style="height:${Math.max(item.laba, item.rugi) / max * 100}%"></i></div>`).join(''); }
function renderPeriods() { const list = document.querySelector('#period-list'); if (!state.periods.length) { list.innerHTML = '<div class="empty-state">Belum ada periode laporan.</div>'; document.querySelector('#report-detail').innerHTML = '<div class="empty-state">Buat periode untuk melihat laporan perubahan ekuitas.</div>'; return; } if (!state.selectedPeriod || !state.periods.some(period => period.id === state.selectedPeriod)) state.selectedPeriod = state.periods[0].id; list.innerHTML = state.periods.map(period => `<div class="period-row"><button class="period-item ${period.id === state.selectedPeriod ? 'active' : ''}" data-period="${period.id}"><span><strong>${period.nama_periode}</strong><span>Modal awal ${money(period.modal_awal)}</span></span><b>›</b></button><button class="period-edit" data-edit-period="${period.id}" title="Edit periode">✎</button></div>`).join(''); const period = state.periods.find(item => item.id === state.selectedPeriod); const month = state.transactions.filter(item => item.tanggal.startsWith(periodMonthKey(period.nama_periode))); const totals = transactionTotals(month); document.querySelector('#report-detail').innerHTML = `<div class="report-header"><div><p class="eyebrow">Laporan perubahan ekuitas</p><h2>${period.nama_periode}</h2><p>Perusahaan Percetakan · Rupiah</p></div><div class="report-brand">PressLedger<br><span>PL</span></div></div><div class="report-lines"><div class="report-line"><span>Modal awal</span><span>${money(period.modal_awal)}</span></div><div class="report-line"><span>(+) Setoran modal</span><span class="amount-positive">${money(totals.setoran)}</span></div><div class="report-line"><span>(−) Prive</span><span class="amount-negative">${money(totals.prive)}</span></div><div class="report-line"><span>(+/-) Laba / rugi periode</span><span class="${totals.laba - totals.rugi >= 0 ? 'amount-positive' : 'amount-negative'}">${money(totals.laba - totals.rugi)}</span></div><div class="report-line total"><span>Modal akhir</span><span>${money(endingCapital(period.modal_awal, totals))}</span></div></div>`; }
function renderAll() { renderStats(); renderOwnerOptions(); renderRecent(); renderOwnerSummary(); renderOwners(); renderTransactions(); renderChart(); renderPeriods(); }
function openModal(id) { document.querySelector(`#${id}`).classList.add('open'); }
function closeModals() { document.querySelectorAll('.modal-backdrop').forEach(modal => modal.classList.remove('open')); }
function setupNavigation() { document.querySelectorAll('.nav-item').forEach(button => button.addEventListener('click', () => switchView(button.dataset.view))); document.querySelectorAll('[data-view-target]').forEach(button => button.addEventListener('click', () => switchView(button.dataset.viewTarget))); }
function switchView(view) { document.querySelectorAll('.page-view').forEach(page => page.classList.remove('active-view')); document.querySelector(`#view-${view}`).classList.add('active-view'); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); }
async function savePeriod() { const form = document.querySelector('#period-form'); if (form.dataset.submitting === 'true') return; form.dataset.submitting = 'true'; const data = Object.fromEntries(new FormData(form).entries()); const periodId = data.id; delete data.id; data.modal_awal = Number(data.modal_awal); try { if (periodId) { const record = await updateRecord('periode_laporan', periodId, data); const index = state.periods.findIndex(item => item.id === periodId); if (index === -1) throw new Error('Periode laporan tidak ditemukan.'); state.periods[index] = record; state.selectedPeriod = periodId; showToast('Periode laporan berhasil diperbarui.'); } else { const record = await insertRecord('periode_laporan', data); state.periods.unshift(record); state.selectedPeriod = record.id; showToast('Periode laporan berhasil dibuat.'); } persist(); form.reset(); document.querySelector('#period-modal-title').textContent = 'Buat periode laporan'; document.querySelector('#period-submit').textContent = 'Buat laporan'; closeModals(); renderAll(); } catch (error) { showToast(error.message || 'Periode laporan gagal disimpan.'); } finally { delete form.dataset.submitting; } }
async function handleSubmit(event) { event.preventDefault(); event.stopPropagation(); const form = event.currentTarget || event.target; if (form.id === 'period-form') { await savePeriod(); return; } if (form.dataset.submitting === 'true') return; form.dataset.submitting = 'true'; const data = Object.fromEntries(new FormData(form).entries()); try { if (form.id === 'owner-form') { const record = await insertRecord('pemilik', data); state.owners.push(record); showToast('Pemilik berhasil ditambahkan.'); } if (form.id === 'transaction-form') { data.jumlah = Number(data.jumlah); if (!['setoran', 'prive'].includes(data.jenis)) data.pemilik_id = null; const record = await insertRecord('transaksi_modal', data); state.transactions.push(record); showToast('Transaksi berhasil dicatat.'); } persist(); form.reset(); closeModals(); renderAll(); } catch (error) { showToast(error.message || 'Data gagal disimpan.'); } finally { delete form.dataset.submitting; } }
async function handleDelete(event) { const ownerId = event.target.dataset.deleteOwner; const transactionId = event.target.dataset.deleteTransaction; try { if (ownerId) { if (state.transactions.some(item => item.pemilik_id === ownerId)) return showToast('Pemilik masih memiliki transaksi.'); if (!confirm('Hapus pemilik ini?')) return; await deleteRecord('pemilik', ownerId); state.owners = state.owners.filter(item => item.id !== ownerId); showToast('Pemilik dihapus.'); } if (transactionId && confirm('Hapus transaksi ini?')) { await deleteRecord('transaksi_modal', transactionId); state.transactions = state.transactions.filter(item => item.id !== transactionId); showToast('Transaksi dihapus.'); } persist(); renderAll(); } catch (error) { showToast(error.message || 'Data gagal dihapus.'); } }
function bindEvents() { setupNavigation(); document.querySelectorAll('[data-open-modal]').forEach(button => button.addEventListener('click', () => { if (button.dataset.openModal === 'period-modal') { document.querySelector('#period-form').reset(); document.querySelector('#period-modal-title').textContent = 'Buat periode laporan'; document.querySelector('#period-submit').textContent = 'Buat laporan'; } openModal(button.dataset.openModal); })); document.querySelectorAll('[data-close-modal]').forEach(button => button.addEventListener('click', closeModals)); document.querySelectorAll('.modal-backdrop').forEach(backdrop => backdrop.addEventListener('click', event => { if (event.target === backdrop) closeModals(); })); document.querySelectorAll('form').forEach(form => form.addEventListener('submit', handleSubmit)); document.querySelector('#period-submit').addEventListener('click', event => { event.preventDefault(); const form = document.querySelector('#period-form'); if (!form.checkValidity()) { form.reportValidity(); return; } savePeriod(); }); document.querySelector('#transaction-type').addEventListener('change', updateOwnerRequirement); document.querySelector('#owners-grid').addEventListener('click', handleDelete); document.querySelector('#transaction-table-body').addEventListener('click', handleDelete); ['transaction-search','transaction-owner-filter','transaction-type-filter','transaction-month-filter'].forEach(id => document.querySelector(`#${id}`).addEventListener('input', renderTransactions)); document.querySelector('#clear-filters').addEventListener('click', () => { document.querySelector('#transaction-search').value = ''; document.querySelector('#transaction-owner-filter').value = ''; document.querySelector('#transaction-type-filter').value = ''; document.querySelector('#transaction-month-filter').value = ''; renderTransactions(); }); document.querySelector('#chart-year').addEventListener('change', renderChart); document.querySelector('#period-list').addEventListener('click', event => { const edit = event.target.closest('[data-edit-period]'); if (edit) { const period = state.periods.find(item => item.id === edit.dataset.editPeriod); const form = document.querySelector('#period-form'); form.elements.id.value = period.id; form.elements.nama_periode.value = period.nama_periode; form.elements.modal_awal.value = period.modal_awal; document.querySelector('#period-modal-title').textContent = 'Edit periode laporan'; document.querySelector('#period-submit').textContent = 'Simpan perubahan'; openModal('period-modal'); return; } const button = event.target.closest('[data-period]'); if (button) { state.selectedPeriod = button.dataset.period; renderPeriods(); } }); document.querySelector('#refresh-btn').addEventListener('click', async () => { try { await loadData(); renderAll(); showToast('Data berhasil dimuat ulang.'); } catch (error) { setConnectionStatus('Gagal terhubung'); showToast(`Supabase: ${error.message || 'koneksi gagal'}`); } }); }
async function init() { seedData(); try { await loadData(); } catch (error) { setConnectionStatus('Gagal terhubung'); showToast(`Supabase: ${error.message || 'koneksi gagal'}`); } document.querySelector('#today-label').textContent = new Intl.DateTimeFormat('id-ID', { dateStyle: 'long' }).format(new Date()); document.querySelector('#chart-year').innerHTML = [...new Set([new Date().getFullYear(), ...state.transactions.map(item => new Date(item.tanggal).getFullYear())])].map(year => `<option>${year}</option>`).join(''); if (!hasSupabaseConfig) setConnectionStatus('Mode demo lokal'); bindEvents(); renderAll(); }
init();
